# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1380206008);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1380206230);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.search.selectedEngine", "DuckDuckGo");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.slowStartup.averageTime", 1361);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20130911164256");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1380292407487");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1380206007487");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1485);
user_pref("datareporting.sessions.current.main", 151);
user_pref("datareporting.sessions.current.sessionRestored", 1579);
user_pref("datareporting.sessions.current.startTime", "1380210003497");
user_pref("datareporting.sessions.current.totalTime", 32);
user_pref("datareporting.sessions.currentIndex", 26);
user_pref("datareporting.sessions.previous.0", "{\"s\":1380206007159,\"a\":8,\"t\":42,\"c\":true,\"m\":41,\"fp\":999,\"sr\":1091}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1380206058877,\"a\":9,\"t\":42,\"c\":true,\"m\":31,\"fp\":1474,\"sr\":1121}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1380207009629,\"a\":9,\"t\":53,\"c\":true,\"m\":30,\"fp\":1225,\"sr\":1387}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1380207069730,\"a\":4,\"t\":29,\"c\":true,\"m\":21,\"fp\":1011,\"sr\":1095}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1380207513304,\"a\":4,\"t\":29,\"c\":true,\"m\":21,\"fp\":1052,\"sr\":958}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1380207566420,\"a\":2,\"t\":16,\"c\":true,\"m\":41,\"fp\":1663,\"sr\":1735}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1380207584279,\"a\":2,\"t\":7,\"c\":true,\"m\":41,\"fp\":1464,\"sr\":1244}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1380207964878,\"a\":1,\"t\":5,\"c\":true,\"m\":30,\"fp\":915,\"sr\":994}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1380207973693,\"a\":1,\"t\":4,\"c\":true,\"m\":81,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.17", "{\"s\":1380208016395,\"a\":7,\"t\":41,\"c\":true,\"m\":63,\"fp\":1416,\"sr\":1287}");
user_pref("datareporting.sessions.previous.18", "{\"s\":1380208064683,\"a\":3,\"t\":37,\"c\":true,\"m\":41,\"fp\":1218,\"sr\":1125}");
user_pref("datareporting.sessions.previous.19", "{\"s\":1380208110295,\"a\":2,\"t\":23,\"c\":true,\"m\":41,\"fp\":1100,\"sr\":979}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1380206110046,\"a\":11,\"t\":137,\"c\":true,\"m\":31,\"fp\":1143,\"sr\":979}");
user_pref("datareporting.sessions.previous.20", "{\"s\":1380209299022,\"a\":1,\"t\":19,\"c\":true,\"m\":111,\"fp\":1465,\"sr\":1280}");
user_pref("datareporting.sessions.previous.21", "{\"s\":1380209330068,\"a\":2,\"t\":59,\"c\":true,\"m\":31,\"fp\":1121,\"sr\":993}");
user_pref("datareporting.sessions.previous.22", "{\"s\":1380209400028,\"a\":8,\"t\":47,\"c\":true,\"m\":41,\"fp\":1770,\"sr\":1578}");
user_pref("datareporting.sessions.previous.23", "{\"s\":1380209715084,\"a\":17,\"t\":83,\"c\":true,\"m\":30,\"fp\":1073,\"sr\":933}");
user_pref("datareporting.sessions.previous.24", "{\"s\":1380209800914,\"a\":12,\"t\":71,\"c\":true,\"m\":21,\"fp\":910,\"sr\":981}");
user_pref("datareporting.sessions.previous.25", "{\"s\":1380209881719,\"a\":14,\"t\":106,\"c\":true,\"m\":31,\"fp\":1091,\"sr\":983}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1380206527005,\"a\":9,\"t\":43,\"c\":true,\"m\":41,\"fp\":1444,\"sr\":1326}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1380206579162,\"a\":6,\"t\":40,\"c\":true,\"m\":31,\"fp\":872,\"sr\":952}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1380206621018,\"a\":10,\"t\":57,\"c\":true,\"m\":31,\"fp\":1390,\"sr\":1560}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1380206683712,\"a\":14,\"t\":71,\"c\":true,\"m\":31,\"fp\":1350,\"sr\":1253}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1380206830314,\"a\":8,\"t\":52,\"c\":true,\"m\":21,\"fp\":1437,\"sr\":1518}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1380206894407,\"a\":7,\"t\":77,\"c\":true,\"m\":31,\"fp\":1067,\"sr\":974}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1380206978573,\"a\":2,\"t\":17,\"c\":true,\"m\":31,\"fp\":1185,\"sr\":1010}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"ipvfox@dagger2-addons.mozilla.org\":{\"version\":\"0.8.3\",\"type\":\"extension\",\"descriptor\":\"/home/clauz/.mozilla/firefox/modh8l6f.default/extensions/ipvfox@dagger2-addons.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.envproxy@as-computer.de.install-event-fired", true);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1363867819000,\"rdfTime\":1353361961000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1380190136000,\"rdfTime\":1378920291000}}},{\"name\":\"app-profile\",\"addons\":{\"envproxy@as-computer.de\":{\"descriptor\":\"/home/clauz/.mozilla/firefox/modh8l6f.default/extensions/envproxy@as-computer.de.xpi\",\"mtime\":1380194119000},\"{dc572301-7619-498c-a57d-39143191b318}\":{\"descriptor\":\"/home/clauz/.mozilla/firefox/modh8l6f.default/extensions/{dc572301-7619-498c-a57d-39143191b318}.xpi\",\"mtime\":1380030522000},\"ipvfox@dagger2-addons.mozilla.org\":{\"descriptor\":\"/home/clauz/.mozilla/firefox/modh8l6f.default/extensions/ipvfox@dagger2-addons.mozilla.org.xpi\",\"mtime\":1368026829000}}}]");
user_pref("extensions.ipvfox@dagger2-addons.mozilla.org.install-event-fired", true);
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.tabmix.version", "0.4.1.1.01");
user_pref("extensions.ubufox@ubuntu.com.install-event-fired", true);
user_pref("extensions.{dc572301-7619-498c-a57d-39143191b318}.install-event-fired", true);
user_pref("gecko.buildID", "20130911164256");
user_pref("gecko.mstone", "24.0");
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.connection-retry-timeout", 3);
user_pref("network.http.max-connections", 1);
user_pref("network.http.max-persistent-connections-per-server", 1);
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.aggressive", true);
user_pref("network.http.proxy.pipelining", true);
/*
user_pref("network.proxy.http", "10.100.5.1");
user_pref("network.proxy.http_port", 8080);
*/
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 1);
user_pref("places.history.expiration.transient_current_max_pages", 38962);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1380210003);
user_pref("toolkit.telemetry.previousBuildID", "20130911164256");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1382798010);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
